### ISSUE TITLE
Can you update the version in releases and the spigot website?

### ISSUE THREAD

**Issue by ghost** [RockinChaos/ItemJoin-Bungee#6]
It would make it more convenient for others to use your plugin.

**Comment by RockinChaos** [comment]
Yes, as with all plugins I develop, this is intended.

CloudSync v1.0.2 is currently in the snapshot phase. Things are kinda borked on Velocity atm so I am working on a recode of that. Once it's complete in the next few days I will be uploading it as an official release.

**Comment by ghost** [comment]
what exactly needs fixing?

**Comment by RockinChaos** [comment]
There were a few various errors but the major one was on certain versions of Velocity, update checking would break causing CloudSync to not load at all.

CloudSync was initially shotty coding so I have spent some time and reworked everything to improve functionality and verbose. Update checking should now be fixed and I added a config.yml that will be generated allowing you to disable update checking and metrics logging.

Furthermore, for improved verbose, I have added some very basic commands that can be accessed via  `/cloudsync` or `/cs`. 
The arguments are; 
- help (requires `cloudsync.use`)
- reload(requires `cloudsync.reload`)
- updates (requires `cloudsync.updates`)
- upgrade (requires `cloudsync.upgrade`)

Documentation on this will be updated once the v1.0.2 is released.

At this point I believe it is ready for release, I did some testing and everything seems to work well on both BungeeCord and Velocity. I think I'll give it a day or so for others to test and if no bugs are reported I will push the release.

If you're interesting in testing you can get the snapshots here; https://ci-dev.craftationgaming.com/job/CloudSync/

**Comment by RockinChaos** [comment]
The official release is now available on SpigotMC.
Link; https://www.spigotmc.org/resources/cloudsync.93382/download?version=562525
